apiVersion: v2
name: ERA
description: A Helm chart for ERA
type: application
version: 1.0.1
appVersion: "3.2.0"

dependencies:
  - name: redis-sentinel
    alias: redis
    version: 1.0.0
    condition: redis.enabled
    repository: "file://../redis-sentinel"